// examples/micro-app/ssr-micro-rsbuild-react/src/app.tsx
import { useRouter } from '@esmx/router-react';
import { useHead } from '@unhead/react';
import { useEffect, useMemo, useState } from 'react';

import { buildSeoHead, Layout, t } from 'ssr-micro-shared/src/index';

const SOURCE_SNIPPET = `import { useState } from 'react'

export function Counter() {
  const [count, setCount] = useState(0)
  return (
    <>
      <p>Count: {count}</p>
      <button onClick={() => setCount(c => c + 1)}>+</button>
      <button onClick={() => setCount(c => c - 1)}>−</button>
    </>
  )
}`;

function Counter() {
    const [count, setCount] = useState(0);
    return (
        <>
            <div className="esmx-stat">
                <div className="esmx-stat__label">Count</div>
                <div className="esmx-stat__value">{count}</div>
            </div>
            <div className="esmx-demo-card__actions">
                <button
                    type="button"
                    className="esmx-btn esmx-btn--primary"
                    onClick={() => setCount((c) => c + 1)}
                >
                    +
                </button>
                <button
                    type="button"
                    className="esmx-btn"
                    onClick={() => setCount((c) => c - 1)}
                >
                    −
                </button>
            </div>
        </>
    );
}

export function AppContent() {
    const router = useRouter();
    const layout = useMemo(
        () => new Layout({ appId: 'react', router }),
        [router]
    );

    useHead(
        buildSeoHead(router, {
            path: '/rsbuild-react/',
            title: t(router, 'fwReactTitle'),
            description: t(router, 'fwReactDesc')
        })
    );

    useEffect(() => {
        layout.mount();
        return () => layout.unmount();
    }, [layout]);

    return (
        <div>
            <div
                id={layout.headerId}
                dangerouslySetInnerHTML={{ __html: layout.header }}
            />
            <main className="esmx-demo-main">
                <article className="esmx-demo-card">
                    <section className="esmx-demo-card__source esmx-code">
                        <header className="esmx-code__header">
                            <span className="esmx-code__file">src/app.tsx</span>
                        </header>
                        <div className="esmx-code__body">
                            <pre>{SOURCE_SNIPPET}</pre>
                        </div>
                    </section>

                    <section className="esmx-demo-card__rendered">
                        <h1 className="esmx-demo-card__title">
                            {t(router, 'fwReactTitle')}
                        </h1>
                        <Counter />
                        <div className="esmx-demo-card__tags">
                            <span className="esmx-badge esmx-badge--react">
                                <span
                                    className="esmx-dot esmx-dot--react"
                                    aria-hidden="true"
                                />
                                React 19
                            </span>
                            <span className="esmx-badge">Rsbuild</span>
                            <span className="esmx-badge">SSR</span>
                        </div>
                    </section>
                </article>

                <footer className="esmx-demo-source">
                    source ·{' '}
                    <code>
                        examples/micro-app/ssr-micro-rsbuild-react/src/app.tsx
                    </code>
                </footer>
            </main>
            <div
                id={layout.footerId}
                dangerouslySetInnerHTML={{ __html: layout.footer }}
            />
        </div>
    );
}

// examples/micro-app/ssr-micro-rsbuild-vue/src/app.vue
<template>
    <div>
        <div :id="layout.headerId" v-html="layout.header"></div>
        <main class="esmx-demo-main">
            <article class="esmx-demo-card">
                <section class="esmx-demo-card__source esmx-code">
                    <header class="esmx-code__header">
                        <span class="esmx-code__file">src/app.vue</span>
                    </header>
                    <div class="esmx-code__body">
                        <pre>{{ sourceSnippet }}</pre>
                    </div>
                </section>

                <section class="esmx-demo-card__rendered">
                    <h1 class="esmx-demo-card__title">{{ title }}</h1>

                    <div class="esmx-stat">
                        <div class="esmx-stat__label">Count</div>
                        <div class="esmx-stat__value">{{ count }}</div>
                    </div>

                    <div class="esmx-demo-card__actions">
                        <button
                            type="button"
                            class="esmx-btn esmx-btn--primary"
                            @click="count++"
                        >
                            +
                        </button>
                        <button
                            type="button"
                            class="esmx-btn"
                            @click="count--"
                        >
                            −
                        </button>
                    </div>

                    <div class="esmx-demo-card__tags">
                        <span class="esmx-badge esmx-badge--vue">
                            <span
                                class="esmx-dot esmx-dot--vue"
                                aria-hidden="true"
                            ></span>
                            Vue 3
                        </span>
                        <span class="esmx-badge">Rsbuild</span>
                        <span class="esmx-badge">SSR</span>
                    </div>
                </section>
            </article>

            <footer class="esmx-demo-source">
                source ·
                <code>examples/micro-app/ssr-micro-rsbuild-vue/src/app.vue</code>
            </footer>
        </main>
        <div :id="layout.footerId" v-html="layout.footer"></div>
    </div>
</template>

<script setup lang="ts">
// CSS imports live in entry.client.ts (browser only) — importing them here
// would route through dev SSR's VM linker, which can't parse CSS.

import { useRouter } from '@esmx/router-vue';
import { useHead } from '@unhead/vue';
import { buildSeoHead, Layout, t } from 'ssr-micro-shared/src/index';
import { onBeforeUnmount, onMounted, ref } from 'vue';

const router = useRouter();
const layout = new Layout({ appId: 'vue3', router });
const count = ref(0);
const title = t(router, 'fwVue3Title');

const sourceSnippet = `<script setup lang="ts">
import { ref } from 'vue'

const count = ref(0)
${'</scr' + 'ipt>'}

<template>
  <p>Count: {{ count }}</p>
  <button @click="count++">+</button>
  <button @click="count--">−</button>
</template>`;

useHead(
    buildSeoHead(router, {
        path: '/rsbuild-vue/',
        title,
        description: t(router, 'fwVue3Desc')
    })
);

onMounted(() => layout.mount());
onBeforeUnmount(() => layout.unmount());
</script>
