// packages/create-esmx/template/react-csr/src/components/hello-world.tsx
import { useState } from 'react';

const SOURCE_SNIPPET = `import { useState } from 'react'

export default function HelloWorld() {
  const [count, setCount] = useState(0)
  return (
    <>
      <p>Count: {count}</p>
      <button onClick={() => setCount(c => c + 1)}>+</button>
      <button onClick={() => setCount(c => c - 1)}>−</button>
    </>
  )
}`;

export default function HelloWorld() {
    const [count, setCount] = useState<number>(0);

    return (
        <>
            <h1 className="demo__title">React 19 CSR</h1>
            <p className="demo__message">
                Mounted in the browser via Esmx + React 19. The counter below is
                reactive.
            </p>
            <div className="demo__code">
                <pre>{SOURCE_SNIPPET}</pre>
            </div>
            <div className="demo__stat">
                <div className="demo__stat-label">Count</div>
                <div className="demo__stat-value">{count}</div>
            </div>
            <div className="demo__actions">
                <button
                    type="button"
                    className="demo__btn demo__btn--primary"
                    onClick={() => setCount((c) => c + 1)}
                >
                    +
                </button>
                <button
                    type="button"
                    className="demo__btn"
                    onClick={() => setCount((c) => c - 1)}
                >
                    −
                </button>
            </div>
            <div className="demo__tags">
                <span className="demo__badge demo__badge--react">
                    <span
                        className="demo__dot demo__dot--react"
                        aria-hidden="true"
                    />
                    React 19
                </span>
                <span className="demo__badge">CSR</span>
            </div>
        </>
    );
}

// packages/create-esmx/template/vue2-csr/src/components/hello-world.vue
<script setup lang="ts">
import { ref } from 'vue';

const count = ref<number>(0);

const sourceSnippet = `<script setup lang="ts">
import { ref } from 'vue'

const count = ref(0)
${'</scr' + 'ipt>'}

<template>
  <p>Count: {{ count }}</p>
  <button @click="count++">+</button>
  <button @click="count--">−</button>
</template>`;
</script>

<template>
    <h1 class="demo__title">Vue 2.7 CSR</h1>
    <p class="demo__message">
        Mounted in the browser via Esmx + Vue 2.7. The counter below is reactive.
    </p>
    <div class="demo__code"><pre>{{ sourceSnippet }}</pre></div>
    <div class="demo__stat">
        <div class="demo__stat-label">Count</div>
        <div class="demo__stat-value">{{ count }}</div>
    </div>
    <div class="demo__actions">
        <button type="button" class="demo__btn demo__btn--primary" @click="count++">+</button>
        <button type="button" class="demo__btn" @click="count--">−</button>
    </div>
    <div class="demo__tags">
        <span class="demo__badge demo__badge--vue">
            <span class="demo__dot demo__dot--vue" aria-hidden="true"></span>
            Vue 2.7
        </span>
        <span class="demo__badge">CSR</span>
    </div>
</template>
