// examples/micro-app/ssr-micro-solid/src/app.tsx
import { createSignal, onCleanup, onMount } from 'solid-js';

import { Layout, t } from 'ssr-micro-shared/index';
import { highlightedSnippet } from './snippet.generated';

function Counter() {
    const [count, setCount] = createSignal(0);
    return (
        <>
            <div class="esmx-stat">
                <div class="esmx-stat__label">Count</div>
                <div class="esmx-stat__value">{count()}</div>
            </div>
            <div class="esmx-demo-card__actions">
                <button
                    type="button"
                    class="esmx-btn esmx-btn--primary"
                    onClick={() => setCount((c) => c + 1)}
                >
                    +
                </button>
                <button
                    type="button"
                    class="esmx-btn"
                    onClick={() => setCount((c) => c - 1)}
                >
                    −
                </button>
            </div>
        </>
    );
}

export function AppContent(props: { router: any }) {
    const layout = new Layout({ appId: 'solid', router: props.router });

    onMount(() => {
        layout.mount();
    });

    onCleanup(() => {
        layout.unmount();
    });

    return (
        <div>
            <div id={layout.headerId} innerHTML={layout.header} />
            <main class="esmx-demo-main">
                <article class="esmx-demo-card">
                    <section class="esmx-demo-card__source esmx-code">
                        <header class="esmx-code__header">
                            <span class="esmx-code__file">src/app.tsx</span>
                        </header>
                        <div class="esmx-code__body">
                            <div innerHTML={highlightedSnippet} />
                        </div>
                    </section>

                    <section class="esmx-demo-card__rendered">
                        <h1 class="esmx-demo-card__title">
                            {t(props.router, 'fwSolidTitle')}
                        </h1>
                        <Counter />
                        <div class="esmx-demo-card__tags">
                            <span class="esmx-badge esmx-badge--solid">
                                <span
                                    class="esmx-dot esmx-dot--solid"
                                    aria-hidden="true"
                                />
                                SolidJS
                            </span>
                            <span class="esmx-badge">Rspack</span>
                            <span class="esmx-badge">SSR</span>
                        </div>
                    </section>
                </article>

                <footer class="esmx-demo-source">
                    source ·{' '}
                    <code>examples/micro-app/ssr-micro-solid/src/app.tsx</code>
                </footer>
            </main>
            <div id={layout.footerId} innerHTML={layout.footer} />
        </div>
    );
}

// examples/micro-app/ssr-micro-preact/src/app.tsx
import type { Router } from '@esmx/router';
import { useEffect, useMemo, useState } from 'preact/hooks';

import { Layout, t } from 'ssr-micro-shared/index';
import { highlightedSnippet } from './snippet.generated';

function Counter() {
    const [count, setCount] = useState(0);
    return (
        <>
            <div class="esmx-stat">
                <div class="esmx-stat__label">Count</div>
                <div class="esmx-stat__value">{count}</div>
            </div>
            <div class="esmx-demo-card__actions">
                <button
                    type="button"
                    class="esmx-btn esmx-btn--primary"
                    onClick={() => setCount((c) => c + 1)}
                >
                    +
                </button>
                <button
                    type="button"
                    class="esmx-btn"
                    onClick={() => setCount((c) => c - 1)}
                >
                    −
                </button>
            </div>
        </>
    );
}

export function AppContent({ router }: { router: Router }) {
    const layout = useMemo(
        () => new Layout({ appId: 'preact', router }),
        [router]
    );

    useEffect(() => {
        layout.mount();
        return () => layout.unmount();
    }, [layout]);

    return (
        <div>
            <div
                id={layout.headerId}
                dangerouslySetInnerHTML={{ __html: layout.header }}
            />
            <main class="esmx-demo-main">
                <article class="esmx-demo-card">
                    <section class="esmx-demo-card__source esmx-code">
                        <header class="esmx-code__header">
                            <span class="esmx-code__file">src/app.tsx</span>
                        </header>
                        <div class="esmx-code__body">
                            <div
                                dangerouslySetInnerHTML={{
                                    __html: highlightedSnippet
                                }}
                            />
                        </div>
                    </section>

                    <section class="esmx-demo-card__rendered">
                        <h1 class="esmx-demo-card__title">
                            {t(router, 'fwPreactTitle')}
                        </h1>
                        <Counter />
                        <div class="esmx-demo-card__tags">
                            <span class="esmx-badge esmx-badge--preact">
                                <span
                                    class="esmx-dot esmx-dot--preact"
                                    aria-hidden="true"
                                />
                                Preact 10
                            </span>
                            <span class="esmx-badge">Rspack</span>
                            <span class="esmx-badge">SSR</span>
                        </div>
                    </section>
                </article>

                <footer class="esmx-demo-source">
                    source ·{' '}
                    <code>examples/micro-app/ssr-micro-preact/src/app.tsx</code>
                </footer>
            </main>
            <div
                id={layout.footerId}
                dangerouslySetInnerHTML={{ __html: layout.footer }}
            />
        </div>
    );
}
