// examples/micro-app/ssr-micro-preact/src/create-app.tsx
import type { RouterMicroAppOptions } from '@esmx/router';
import { hydrate, render } from 'preact';
import { renderToString } from 'preact-render-to-string';

import { BaseApp } from 'ssr-micro-shared/src/index';
import { AppContent } from './app';

class PreactApp extends BaseApp {
    constructor(router) {
        super(router);
        this.head.push({
            title: 'Preact Micro-App',
            meta: [
                {
                    name: 'description',
                    content: 'This page is rendered by a Preact 10 micro-app.'
                }
            ]
        });
    }

    protected onMount(container: HTMLElement): void {
        render(<AppContent router={this.router} />, container);
    }

    protected onHydration(container: HTMLElement): void {
        hydrate(<AppContent router={this.router} />, container);
    }

    protected onUnmount(): void {
        if (this.container) {
            render(null, this.container);
        }
    }

    async renderToString(): Promise<string> {
        return renderToString(<AppContent router={this.router} />);
    }
}

export function createPreactApp(router): RouterMicroAppOptions {
    const app = new PreactApp(router);
    return {
        mount: (el) => app.mount(el),
        hydration: (el) => app.hydration(el),
        unmount: () => app.unmount(),
        renderToString: () => app.renderToString()
    };
}

// examples/micro-app/ssr-micro-solid/src/create-app.tsx
import type { RouterMicroAppOptions } from '@esmx/router';
import { hydrate, render, renderToString } from 'solid-js/web';

import { BaseApp } from 'ssr-micro-shared/src/index';
import { AppContent } from './app';

class SolidApp extends BaseApp {
    private dispose: (() => void) | null = null;

    constructor(router) {
        super(router);
        this.head.push({
            title: 'SolidJS Micro-App',
            meta: [
                {
                    name: 'description',
                    content: 'This page is rendered by a SolidJS micro-app.'
                }
            ]
        });
    }

    protected onMount(container: HTMLElement): void {
        this.dispose = render(
            () => <AppContent router={this.router} />,
            container
        );
    }

    protected onHydration(container: HTMLElement): void {
        this.dispose = hydrate(
            () => <AppContent router={this.router} />,
            container
        );
    }

    protected onUnmount(): void {
        this.dispose?.();
        this.dispose = null;
    }

    async renderToString(): Promise<string> {
        return renderToString(() => <AppContent router={this.router} />);
    }
}

export function createSolidApp(router): RouterMicroAppOptions {
    const app = new SolidApp(router);
    return {
        mount: (el) => app.mount(el),
        hydration: (el) => app.hydration(el),
        unmount: () => app.unmount(),
        renderToString: () => app.renderToString()
    };
}
