// examples/micro-app/ssr-micro-react/src/create-app.tsx
import type { RouterMicroAppOptions } from '@esmx/router';
import { RouterProvider } from '@esmx/router-react';
import { createHead, UnheadProvider } from '@unhead/react/client';
import { createRoot, hydrateRoot } from 'react-dom/client';
import { renderToString } from 'react-dom/server';
import React from 'react';

import { BaseApp, setRouterHead } from 'ssr-micro-shared/src/index';
import { AppContent } from './app';

function createApp(router, head) {
    return () => (
        <UnheadProvider head={head}>
            <RouterProvider router={router}>
                <AppContent />
            </RouterProvider>
        </UnheadProvider>
    );
}

class ReactApp extends BaseApp {
    private reactRoot: ReturnType<typeof createRoot> | null = null;
    private head = createHead();

    constructor(router) {
        super(router);
        setRouterHead(router, this.head);
    }

    protected onMount(container: HTMLElement): void {
        const App = createApp(this.router, this.head);
        this.reactRoot = createRoot(container);
        this.reactRoot.render(<App />);
    }

    protected onHydration(container: HTMLElement): void {
        const App = createApp(this.router, this.head);
        this.reactRoot = hydrateRoot(container, <App />);
    }

    protected onUnmount(): void {
        this.reactRoot?.unmount();
        this.reactRoot = null;
    }

    async renderToString(): Promise<string> {
        const App = createApp(this.router, this.head);
        const html = renderToString(<App />);
        return html?.trim() ? `<div>${html}</div>` : '';
    }
}

export function createReactApp(router): RouterMicroAppOptions {
    const app = new ReactApp(router);
    return {
        mount: (el) => app.mount(el),
        hydration: (el) => app.hydration(el),
        unmount: () => app.unmount(),
        renderToString: () => app.renderToString()
    };
}

// examples/micro-app/ssr-micro-solid/src/create-app.tsx
import type { RouterMicroAppOptions } from '@esmx/router';
import { hydrate, render, renderToString } from 'solid-js/web';

import { BaseApp } from 'ssr-micro-shared/src/index';
import { AppContent } from './app';

class SolidApp extends BaseApp {
    private dispose: (() => void) | null = null;

    constructor(router) {
        super(router);
        this.head.push({
            title: 'SolidJS Micro-App',
            meta: [
                {
                    name: 'description',
                    content: 'This page is rendered by a SolidJS micro-app.'
                }
            ]
        });
    }

    protected onMount(container: HTMLElement): void {
        this.dispose = render(
            () => <AppContent router={this.router} />,
            container
        );
    }

    protected onHydration(container: HTMLElement): void {
        this.dispose = hydrate(
            () => <AppContent router={this.router} />,
            container
        );
    }

    protected onUnmount(): void {
        this.dispose?.();
        this.dispose = null;
    }

    async renderToString(): Promise<string> {
        const html = renderToString(() => <AppContent router={this.router} />);
        return html?.trim() ? `<div>${html}</div>` : '';
    }
}

export function createSolidApp(router): RouterMicroAppOptions {
    const app = new SolidApp(router);
    return {
        mount: (el) => app.mount(el),
        hydration: (el) => app.hydration(el),
        unmount: () => app.unmount(),
        renderToString: () => app.renderToString()
    };
}
